### ISSUE TITLE
Startup Errors (Tag is Protected)

### ISSUE THREAD

**Issue by phenomax** [rnlg/LiteRed2#5]
Hi,
using the most recent `LiteRed v2.024, LiteRed2024.m (CRC32:1482835175,{2340977437, 3317197336, 2439625558})`, 
multiple errors are thrown after loading the package:

Used Code: 
```
SetDirectory[NotebookDirectory[]]
<< LiteRed2`
```

Errors:
<img width="1043" alt="image" src="https://github.com/rnlg/LiteRed2/assets/12475496/3bad7688-5277-4205-a23b-8ece05947c9b">

Tested Mathematica Versions: `12.1.1.0`, `14.0.0.0`

**Comment by rnlg** [comment]
@phenomax Looks like you loaded LiteRed2 twice. If you have the command 
```
<< LiteRed2`
```
in the initialization cell (usually greyed background) of Mathematica notebook and evaluate it with Shift-Enter, then Mathematica asks whether you want to evaluate the initialization. If you say 'Yes', the code  ``<< LiteRed2` `` is evaluated twice.

**Comment by phenomax** [comment]
@rnlg Thank you very much, that was precisely the issue!
