### ISSUE TITLE
A question regarding FindSymmetries

### ISSUE THREAD

**Issue by vsht** [rnlg/LiteRed2#7]
Hi,

I noticed that in the following example 

```
SetDim[d];
Declare[
  {k1, n, nb}, Vector,
  {mqb, u0b}, Number
  ];
p3 = p1 + p2;
SetConstraints[{n, nb},
  sp[n] = 0; sp[nb] = 0; sp[n, nb] = 2;
  ];

NewDsBasis[topo1, {sp[k1] + sp[k1, n]*mqb + sp[k1, nb]*mqb, 
  sp[k1] + 2*sp[k1, n] + (sp[k1, nb])/2 - 
   2*sp[k1, n]*u0b - (sp[k1, nb]*u0b)/2, 
  sp[k1] + 2*sp[k1, n] + (sp[k1, nb])/2 - u0b/2 - sp[k1, n]*u0b - 
   sp[k1, nb]*u0b}, {k1}]

GenerateIBP[topo1]
AnalyzeSectors[topo1]
FindSymmetries[topo1]
```

LiteRed 2 returns
```
During evaluation of In[12]:= Solve::svars: Equations may not give solutions for all "solve" variables.

During evaluation of In[12]:= Solve::svars: Equations may not give solutions for all "solve" variables.

During evaluation of In[12]:= FindSymmetries::ems: Option EMs->True probably resulted in continuous symmetries. Try to replace it with EMs->False. Aborting...

Out[12]= $Aborted
```
Is this something expected? The issue is also relevant for FIRE 6 that still uses an older version of LR:
https://gitlab.com/feynmanintegrals/fire/-/issues/33

**Comment by rnlg** [comment]
Hi, Vladislav,
This means that there are continuous symmetries wrt external momenta. For example, this may happen for the  diagrams with two massless legs, k1 and k2, and one offshell leg (form factors). Then we can rescale `k1->a k1,k2->k2/a` with arbitrary `a`, and none of the three invariants `sp[k1],sp[k2],sp[k1,k2]` will change. Meanwhile LiteRed can use only discrete symmetries. So, you should give LiteRed a clue which discrete symmetries you want to take into account. This is done by option `EMs` of `FindSymmetries` (and `FindExtSymmetries`).
For example, you can use `EMs->{{},{k1->k2,k2->k1}}`, where `{}` denotes identical substitution and  `{k1->k2,k2->k1}` denotes swapping of external momenta. In fact, if (some of) your substitutions are inconsistent, i.e. lead to the change of external invariants, LiteRed will notice this, complain, and skip those.  So if LiteRed does not complain, your substitutions are indeed symmetries.

**Comment by vsht** [comment]
Hi Roman,

thanks a lot for your explanation. Since I'm only interested in using LiteRed as a way to speed up the FIRE reduction,
the current behavior of the code is somewhat difficult to handle in an automated script.

I wonder if it would be possible to monkey patch LR 1.83 in such a way, that in the case of continuous symmetries
no symmetries at all shall be returned. So one could just skip this step but still benefit from the information obtained
from AnalyzeSectors?

Cheers,
Vlad

**Comment by rnlg** [comment]
Well, how about `CheckAbort[FindSymmetries[topo1],FindSymmetries[topo1,EMs->False]]`?
Anyway, the patch I can immediately see is of this kind. You can mute warnings as usual,
`Quiet[CheckAbort[FindSymmetries[topo1],FindSymmetries[topo1,EMs->False]]]`

**Comment by vsht** [comment]
Many thanks!

**Comment by vsht** [comment]
Hi Roman,

coming back to the same topology (where I initially set two variables to 1). It seems like now FindSymmetries
cannot even terminate:

```
SetDim[d];
Declare[{k1, n, nb}, Vector, {mqb, u0b, meta, gkin}, Number];
p3 = p1 + p2;
SetConstraints[{n, nb}, sp[n] = 0; sp[nb] = 0; sp[n, nb] = 2;];
NewDsBasis[topo1, {sp[k1] + sp[k1, n]*mqb + sp[k1, nb]*mqb, 
    sp[k1] + 2*gkin*meta*sp[k1, n] + (meta sp[k1, nb])/(2 gkin) - 
      2*gkin*meta*sp[k1, n]*u0b - (meta*sp[k1, nb]*u0b)/(2 gkin), 
    sp[k1] + mqb*sp[k1, n] + mqb*sp[k1, nb] + 
   2*meta*mqb*u0b - (meta*mqb*u0b)/(2*gkin) - 2*gkin*meta*mqb*u0b + 
   meta*sp[k1, n]*u0b - 2*gkin*meta*sp[k1, n]*u0b + 
   meta*sp[k1, nb]*u0b - (meta*sp[k1, nb]*u0b)/(2*gkin) + 
   2*meta^2*u0b^2 - (meta^2*u0b^2)/(2*gkin) - 2*gkin*meta^2*u0b^2
    }, {k1}]

GenerateIBP[topo1]
AnalyzeSectors[topo1]
FindSymmetries[topo1]
```

**Comment by rnlg** [comment]
Many parameters slow down `GroebnerBasis` routine used in `FindSymmetries`. The slow down seems to occur only when there are continuous symmetries.

Commit (f70ef4f3525e460e5a6642012e71dafcb3344726) introduces option  `GroebnerBasis` of `FindSymmetries` (set to `True` by default to be compatible with previous behaviour), which allows to turn off Groebner basis calculation (try `FindSymmetries[topo1,GroebnerBasis->False]`).
